"""Application state in Postgres: jobs, publications and notifications.

See schema.py for what the tables are and why each constraint exists. This module is the Python
side of the contract; web/lib/appstate.ts is the TypeScript side, and both apply the same numbered
migrations from the same list.
"""
from __future__ import annotations

import os
import secrets
import time
from typing import Any

from .schema import ADVISORY_LOCK_KEY, BOOTSTRAP, LATEST, MIGRATIONS

_ALPHABET = "0123456789abcdefghjkmnpqrstvwxyz"   # Crockford base32, lower case: sortable, unambiguous


def new_id(prefix: str) -> str:
    """`<prefix>_` + 10 characters of millisecond time + 16 of randomness.

    Time first, so ids sort in creation order and a list of jobs needs no second key; randomness
    second, so two ids created in the same millisecond on two machines still differ. The same shape
    as web/lib/ids.ts produces.
    """
    ms = int(time.time() * 1000)
    head = ""
    for _ in range(10):
        head = _ALPHABET[ms % 32] + head
        ms //= 32
    tail = "".join(secrets.choice(_ALPHABET) for _ in range(16))
    return f"{prefix}_{head}{tail}"


JOB_ID_PATTERN = r"^job_[0-9a-hjkmnp-tv-z]{26}$"


def environment() -> str:
    """Which deployment this process belongs to.

    Rows carry their environment so that a preview and production sharing one database — which the
    Neon integration permits — can never act on each other's jobs or email each other's recipients.
    """
    value = (os.environ.get("AZMONITOR_ENVIRONMENT") or os.environ.get("VERCEL_ENV") or "development").strip()
    return value if value in ("production", "preview", "development", "test") else "development"


def migrate(conn, applied_by: str = "worker") -> list[int]:
    """Apply every migration not yet recorded. Safe to call from any number of processes at once."""
    applied: list[int] = []
    with conn.transaction():
        with conn.cursor() as cur:
            cur.execute("SELECT pg_advisory_xact_lock(%s)", (ADVISORY_LOCK_KEY,))
            cur.execute(BOOTSTRAP)
            cur.execute("SELECT version FROM schema_migrations")
            done = {row[0] for row in cur.fetchall()}
            for version, name, sql in MIGRATIONS:
                if version in done:
                    continue
                cur.execute(sql)
                cur.execute("INSERT INTO schema_migrations(version, name, applied_by) VALUES (%s, %s, %s)",
                            (version, name, applied_by))
                applied.append(version)
    return applied


def schema_version(conn) -> int:
    with conn.cursor() as cur:
        cur.execute("SELECT to_regclass('schema_migrations')")
        if cur.fetchone()[0] is None:
            return 0
        cur.execute("SELECT coalesce(max(version), 0) FROM schema_migrations")
        return int(cur.fetchone()[0])


def export_typescript() -> str:
    """The migrations as a TypeScript module, so the web application applies exactly these."""
    import json

    lines = [
        "// GENERATED by `python -m azmonitor.appstate export-ts` from azmonitor/appstate/schema.py.",
        "// Do not edit by hand: tests/test_appstate.py fails if this file and the Python list differ.",
        "",
        "export interface Migration { version: number; name: string; sql: string }",
        "",
        f"export const ADVISORY_LOCK_KEY = {json.dumps(str(ADVISORY_LOCK_KEY))};",
        f"export const LATEST = {LATEST};",
        f"export const BOOTSTRAP = {json.dumps(BOOTSTRAP)};",
        "",
        "export const MIGRATIONS: Migration[] = [",
    ]
    for version, name, sql in MIGRATIONS:
        lines.append(f"  {{ version: {version}, name: {json.dumps(name)}, sql: {json.dumps(sql)} }},")
    lines.append("];")
    return "\n".join(lines) + "\n"


__all__ = ["new_id", "environment", "migrate", "schema_version", "export_typescript",
           "JOB_ID_PATTERN", "LATEST", "MIGRATIONS"]
