"""Collection pipeline: discover -> fetch -> parse -> validate -> store (append-only vintages)."""
from __future__ import annotations

import datetime as dt
import json
import re
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Any

from . import config
from .discovery import DiscoveredDocument, _edition_period, discover
from .ingest.fetch import FetchError, Fetcher
from .parsers.base import Observation, ParseResult, ParserError
from .parsers.registry import get_parser
from .storage.db import Database, utcnow
from .util.log import get_logger, setup_logging
from .util.periods import ym

log = get_logger("pipeline")


class Pipeline:
    def __init__(self, offline: bool = False):
        self.settings = config.settings()
        self.paths = config.paths()
        self.paths.ensure()
        setup_logging(self.paths.logs_dir)
        self.db = Database(self.paths.db_path)
        self.fetcher = Fetcher(self.settings.get("http", {}), self.paths.raw_dir, offline=offline)
        self.sources = config.sources().get("sources", {})
        self._register_series()

    # ------------------------------------------------------------------ registry
    def _register_series(self) -> None:
        for sid, scfg, ds in config.iter_datasets():
            p = ds.get("parse") or {}
            for s in (p.get("series") or []) + (p.get("rows") or []):
                self.db.register_series({
                    "series_id": s["id"], "dataset_id": ds["id"], "source_id": sid, "label_en": s.get("label_en"), "label_az": s.get("label_az"),
                    "unit": s.get("unit", p.get("unit")), "population": s.get("population", p.get("population")),
                    "period_type": p.get("period_type"), "frequency": ds.get("frequency"),
                })
        # SSC headline rows are generated by the parser from a fixed row list; register English labels for them
        from .parsers.ssc_headline import HEADLINE_ROWS
        from .parsers.ssc_html import NOMINAL_KEYS

        ptype = {"ytd_flow": "ytd_flow", "ytd_average": "ytd_average", "stock": "month_end_stock", "growth_only": "ytd_growth_yoy"}
        for r in HEADLINE_ROWS:
            level_label = r.label_en.replace(" and real growth", "").replace(", nominal growth", "")
            growth_label = level_label if r.kind == "growth_only" else f"{level_label.replace(', nominal', '')}, {'nominal' if r.key in NOMINAL_KEYS else 'real'} growth y/y"
            for suffix, label, unit, pt in (("level", level_label, r.unit, ptype[r.kind]), ("growth", growth_label, "%", "ytd_growth_yoy" if r.kind != "stock" else "stock_growth_yoy")):
                if r.kind == "growth_only" and suffix == "level":
                    continue
                self.db.register_series({"series_id": f"ssc.hl.{r.key}.{suffix}", "dataset_id": "ssc_macro_headline_html", "source_id": "SSC_MACRO",
                                         "label_en": label, "label_az": None, "unit": unit, "population": "national (SSC)", "period_type": pt, "frequency": "M"})

    # ------------------------------------------------------------------ discovery
    def discover(self, source_ids: list[str] | None = None, history_start: str | None = None) -> list[DiscoveredDocument]:
        out: list[DiscoveredDocument] = []
        history_start = history_start or self.settings.get("history_start", "2020-01")
        for sid, scfg in self.sources.items():
            if source_ids and sid not in source_ids:
                continue
            try:
                docs = discover(sid, scfg, self.fetcher, history_start=history_start)
            except FetchError as exc:
                log.error("discovery failed for %s: %s", sid, exc)
                self.db.log_event("discovery_failed", None, None, {"source_id": sid, "error": str(exc)})
                continue
            for d in docs:
                self.db.record_link({
                    "source_id": d.source_id, "dataset_id": d.dataset_id, "discovery_url": d.discovery_url, "document_url": d.document_url,
                    "title": d.title, "size_text": d.size_text, "published_at": d.published_at.isoformat() if d.published_at else None,
                    "published_at_basis": d.published_at_basis,
                })
            out.extend(docs)
        return out

    # ------------------------------------------------------------------ selection
    @staticmethod
    def _doc_year(d: DiscoveredDocument) -> int | None:
        m = re.search(r"(20\d{2})", d.document_url.rsplit("/", 1)[-1]) or re.search(r"(20\d{2})", d.title)
        if m:
            return int(m.group(1))
        return d.published_at.year if d.published_at else None

    def select_documents(self, docs: list[DiscoveredDocument], ds: dict[str, Any], history_start: str) -> list[DiscoveredDocument]:
        cand = [d for d in docs if d.dataset_id == ds["id"]]
        if not cand:
            return []
        if ds.get("download") == "latest_only" or not ds.get("multi_document"):
            cand.sort(key=lambda d: (d.published_at or dt.date.min, d.document_url))
            return [cand[-1]]
        start_year = int(history_start[:4]) - (1 if ds["id"].startswith("cba_bank_") else 0)
        keep = []
        for d in cand:
            y = self._doc_year(d)
            if y is None or y >= start_year:
                keep.append(d)
        # oldest edition first so that the newest publication ends up as the current vintage
        keep.sort(key=lambda d: (d.extra.get("edition_period") or "", d.published_at or dt.date.min, self._doc_year(d) or 0, d.document_url))
        return keep

    # ------------------------------------------------------------------ fetch + parse
    def process_document(self, d: DiscoveredDocument, sid: str, ds: dict[str, Any], run_stats: dict[str, Any]) -> None:
        dsid = ds["id"]
        st = run_stats.setdefault(dsid, {"checked": 0, "new_docs": 0, "unchanged": 0, "new_obs": 0, "revisions": 0, "errors": [], "warnings": []})
        st["checked"] += 1
        try:
            fetched = self.fetcher.get(d.document_url, allow_html=(d.extension == "html"))
        except FetchError as exc:
            st["errors"].append(f"fetch: {exc}")
            self.db.log_event("fetch_failed", None, dsid, {"url": d.document_url, "error": str(exc)})
            self.db.set_dataset_state(dsid, source_id=sid, last_checked_at=utcnow(), status="fetch_failed", message=str(exc))
            return
        if d.extension == "html":
            # HTML pages carry volatile markup; fingerprint the article content so an unchanged page is recognised
            fetched.sha256 = html_content_fingerprint(fetched.content)
        doc_id = f"{dsid}:{fetched.sha256[:16]}"
        existing = self.db.get_document(doc_id)
        if existing is not None and existing["status"] == "parsed":
            st["unchanged"] += 1
            self.db.set_dataset_state(dsid, source_id=sid, last_checked_at=utcnow(), status="unchanged")
            return
        path = self.fetcher.store(dsid, fetched)
        prior_docs = self.db.documents_for_dataset(dsid)
        replaced = [p for p in prior_docs if p["document_url"] == d.document_url and p["sha256"] != fetched.sha256]
        rec = {
            "doc_id": doc_id, "source_id": sid, "dataset_id": dsid, "discovery_url": d.discovery_url, "document_url": d.document_url,
            "title_original": d.title, "title_en": ds.get("title_en"), "content_type": fetched.content_type, "sha256": fetched.sha256,
            "size_bytes": len(fetched.content), "stored_path": str(path.relative_to(self.paths.data_dir)), "retrieved_at": fetched.retrieved_at,
            "first_seen_at": existing["first_seen_at"] if existing else fetched.retrieved_at,
            "published_at": d.published_at.isoformat() if d.published_at else None, "published_at_basis": d.published_at_basis,
            "http_last_modified": fetched.last_modified, "status": "downloaded", "note": ("replaces " + replaced[-1]["doc_id"]) if replaced else None,
        }
        self.db.upsert_document(rec)
        self.db.log_event("replaced" if replaced else "downloaded", doc_id, dsid, {"url": d.document_url, "sha256": fetched.sha256})
        st["new_docs"] += 1
        parser = get_parser(ds.get("parser"))
        if parser is None:
            rec["status"] = "stored"
            self.db.upsert_document(rec)
            self.db.set_dataset_state(dsid, source_id=sid, last_doc_id=doc_id, last_sha256=fetched.sha256, last_checked_at=utcnow(),
                                      last_changed_at=utcnow(), status="stored")
            return
        context = self._context_for(ds, d)
        try:
            result: ParseResult = parser(path, ds.get("parse") or {}, source_id=sid, dataset_id=dsid, context=context)
        except Exception as exc:  # any parser crash is a parser failure; it must never abort the run or touch stored data
            log.exception("parser failed for %s", d.document_url)
            st["errors"].append(f"parse {d.title[:40]}: {type(exc).__name__}: {exc}")
            rec["status"] = "parse_failed"
            rec["note"] = str(exc)[:300]
            self.db.upsert_document(rec)
            self.db.log_event("parse_failed", doc_id, dsid, {"error": str(exc)})
            self.db.set_dataset_state(dsid, source_id=sid, last_checked_at=utcnow(), status="parse_failed", message=str(exc)[:300])
            return
        if result.errors:
            st["errors"].extend(f"{d.title[:40]}: {e}" for e in result.errors)
            rec["status"] = "parse_failed"
            rec["note"] = "; ".join(result.errors)[:300]
            self.db.upsert_document(rec)
            self.db.log_event("parse_failed", doc_id, dsid, {"errors": result.errors})
            self.db.set_dataset_state(dsid, source_id=sid, last_checked_at=utcnow(), status="parse_failed", message="; ".join(result.errors)[:300])
            return
        st["warnings"].extend(f"{d.title[:40]}: {w}" for w in result.warnings)
        checks = run_dataset_checks(ds, result.observations)
        failed = [c for c in checks if not c["ok"]]
        if failed:
            st["warnings"].extend(f"check {c['type']} {c['total']} {c['period_end']}: diff {c['diff']:.3f}" for c in failed[:5])
        materiality = self._materiality_for(ds)
        stats = self.db.store_observations(dsid, doc_id, result.observations, materiality=materiality, published_at=rec["published_at"])
        st["new_obs"] += stats["n_new"]
        st["revisions"] += stats["n_revisions"]
        rec["status"] = "parsed"
        self.db.upsert_document(rec)
        latest = self._latest_period(dsid)
        self.db.log_event("parsed", doc_id, dsid, {"n_obs": stats["n_obs"], "n_new": stats["n_new"], "n_revisions": stats["n_revisions"],
                                                  "checks_failed": len(failed), "meta": result.meta})
        self.db.set_dataset_state(dsid, source_id=sid, last_doc_id=doc_id, last_sha256=fetched.sha256, last_checked_at=utcnow(),
                                  last_changed_at=utcnow() if (stats["n_new"] or stats["n_revisions"]) else None,
                                  latest_period_end=latest.isoformat() if latest else None,
                                  status="parsed" + ("_with_check_failures" if failed else ""),
                                  message=f"{stats['n_new']} new, {stats['n_revisions']} revised, {stats['n_unchanged']} unchanged")
        if stats["n_revisions"]:
            log.info("%s: %d revisions detected (vintage %s)", dsid, stats["n_revisions"], stats["vintage_id"])

    def _latest_period(self, dataset_id: str) -> dt.date | None:
        row = self.db.conn.execute("SELECT MAX(period_end) FROM observations WHERE dataset_id=? AND status='current' AND value IS NOT NULL", (dataset_id,)).fetchone()
        return dt.date.fromisoformat(row[0]) if row and row[0] else None

    def _materiality_for(self, ds: dict[str, Any]) -> float:
        m = self.settings.get("materiality", {})
        p = ds.get("parse") or {}
        unit = (p.get("unit") or "").lower()
        if "%" in unit:
            return float(m.get("rate_pct", 0.01))
        if "index" in unit:
            return float(m.get("index", 0.05))
        if "count" in unit:
            return float(m.get("count", 1))
        return float(m.get("stock_azn_mln", 1.0)) * 0.01  # values are stored unrounded; 0.01 mln = 10k AZN

    def _context_for(self, ds: dict[str, Any], d: DiscoveredDocument) -> dict[str, Any]:
        ctx: dict[str, Any] = {"title": d.title, "url": d.document_url, "published_at": d.published_at}
        ep = d.extra.get("edition_period") if d.extra else None
        if not ep and d.title:
            epd = _edition_period(d.title)
            ep = epd.isoformat() if epd else None
        if ep:
            ctx["edition_period"] = ep
        p = ds.get("parse") or {}
        comp = p.get("period_from_dataset")
        if comp:
            rows = self.db.current_observations(dataset_id=comp)
            latest = max((r["period_end"] for r in rows), default=None)
            if latest:
                ctx["period_end"] = dt.date.fromisoformat(latest)
        return ctx

    # ------------------------------------------------------------------ commands
    def refresh(self, source_ids: list[str] | None = None, dataset_ids: list[str] | None = None, history_start: str | None = None) -> dict[str, Any]:
        run_id = f"refresh-{uuid.uuid4().hex[:8]}"
        self.db.start_run(run_id, "refresh")
        history_start = history_start or self.settings.get("history_start", "2020-01")
        stats: dict[str, Any] = {}
        docs = self.discover(source_ids, history_start=history_start)
        for sid, scfg, ds in config.iter_datasets():
            if source_ids and sid not in source_ids:
                continue
            if dataset_ids and ds["id"] not in dataset_ids:
                continue
            selected = self.select_documents(docs, ds, history_start)
            if not selected:
                stats.setdefault(ds["id"], {"checked": 0, "new_docs": 0, "unchanged": 0, "new_obs": 0, "revisions": 0, "errors": [], "warnings": []})
                stats[ds["id"]]["errors"].append("no document discovered for this dataset")
                self.db.set_dataset_state(ds["id"], source_id=sid, last_checked_at=utcnow(), status="not_discovered")
                continue
            # dependent datasets (regional snapshots) after their companions: process in config order, companions listed first
            for d in selected:
                self.process_document(d, sid, ds, stats)
        summary = {"run_id": run_id, "datasets": stats, "finished_at": utcnow()}
        ok = not any(v["errors"] for v in stats.values())
        self.db.finish_run(run_id, "ok" if ok else "partial", summary)
        (self.paths.state_dir / "last_refresh.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2, default=str), encoding="utf-8")
        return summary

    def latest_periods(self) -> dict[str, str | None]:
        return {k: v["latest_period_end"] for k, v in self.db.dataset_states().items()}


    # ------------------------------------------------------------------ reparse
    def reparse(self, dataset_ids: list[str] | None = None) -> dict[str, Any]:
        """Re-run parsers on stored documents (after a parser fix). Produces new vintages only where values change."""
        stats: dict[str, Any] = {}
        for sid, scfg, ds in config.iter_datasets():
            if dataset_ids and ds["id"] not in dataset_ids:
                continue
            parser = get_parser(ds.get("parser"))
            if parser is None:
                continue
            docs = [r for r in self.db.documents_for_dataset(ds["id"]) if r["status"] in ("parsed", "parse_failed", "downloaded")]
            docs.sort(key=lambda r: (r["published_at"] or "", r["retrieved_at"]))
            st = stats.setdefault(ds["id"], {"docs": 0, "new_obs": 0, "revisions": 0, "errors": []})
            for r in docs:
                path = self.paths.data_dir / r["stored_path"]
                if not path.exists():
                    st["errors"].append(f"missing file {r['stored_path']}")
                    continue
                d = DiscoveredDocument(source_id=sid, dataset_id=ds["id"], discovery_url=r["discovery_url"], document_url=r["document_url"],
                                       title=r["title_original"] or "", published_at=dt.date.fromisoformat(r["published_at"]) if r["published_at"] else None)
                try:
                    result = parser(path, ds.get("parse") or {}, source_id=sid, dataset_id=ds["id"], context=self._context_for(ds, d))
                except Exception as exc:
                    st["errors"].append(f"{r['doc_id']}: {type(exc).__name__}: {exc}")
                    self.db.upsert_document({"doc_id": r["doc_id"], "source_id": sid, "dataset_id": ds["id"], "document_url": r["document_url"],
                                             "sha256": r["sha256"], "retrieved_at": r["retrieved_at"], "first_seen_at": r["first_seen_at"],
                                             "status": "parse_failed", "note": str(exc)[:300]})
                    continue
                if result.errors:
                    st["errors"].append(f"{r['doc_id']}: {'; '.join(result.errors)}")
                    continue
                out = self.db.store_observations(ds["id"], r["doc_id"], result.observations, materiality=self._materiality_for(ds), published_at=r["published_at"])
                st["docs"] += 1
                st["new_obs"] += out["n_new"]
                st["revisions"] += out["n_revisions"]
                self.db.upsert_document({"doc_id": r["doc_id"], "source_id": sid, "dataset_id": ds["id"], "document_url": r["document_url"],
                                         "sha256": r["sha256"], "retrieved_at": r["retrieved_at"], "first_seen_at": r["first_seen_at"], "status": "parsed", "note": None})
                latest = self._latest_period(ds["id"])
                self.db.set_dataset_state(ds["id"], source_id=sid, latest_period_end=latest.isoformat() if latest else None, status="parsed",
                                          message=f"reparse: {out['n_new']} new, {out['n_revisions']} revised")
        return stats


def html_content_fingerprint(content: bytes) -> str:
    import hashlib

    from bs4 import BeautifulSoup

    soup = BeautifulSoup(content, "html.parser")
    node = soup.select_one(".single-news") or soup.select_one("#macro_iq") or soup.select_one("#tmacro") or soup
    text = " ".join(node.get_text(" ", strip=True).split())
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------- checks

def run_dataset_checks(ds: dict[str, Any], obs: list[Observation]) -> list[dict[str, Any]]:
    """Source totals vs components within tolerance, per period (and per dims when configured)."""
    p = ds.get("parse") or {}
    checks = p.get("checks") or []
    if not checks:
        return []
    by: dict[tuple[str, str, str], float | None] = {}
    for o in obs:
        key = (o.series_id, json.dumps(o.dims, sort_keys=True), o.period_end.isoformat())
        by[key] = o.value
    out = []
    periods = sorted({o.period_end.isoformat() for o in obs})
    for c in checks:
        if c.get("type") != "components_sum":
            continue
        dims = json.dumps(c.get("dims", {}), sort_keys=True)
        tol = float(c.get("tolerance", 0.5))
        for pe in periods:
            total = by.get((c["total"], dims, pe))
            if total is None:
                continue
            s = 0.0
            complete = True
            for part in c["parts"]:
                sign = -1.0 if part.startswith("-") else 1.0
                v = by.get((part.lstrip("-"), dims, pe))
                if v is None:
                    complete = False
                    break
                s += sign * v
            if not complete:
                continue
            diff = total - s
            out.append({"type": "components_sum", "total": c["total"], "period_end": pe, "diff": diff, "ok": abs(diff) <= tol, "tolerance": tol})
    return out
